### ISSUE TITLE
How to convert pdb file to WebDataset format？

### ISSUE THREAD

**Issue by xin-yang123** [MadryLab/rla#1]
Hi author! Thank you for your great work of RLA!

I saw that you provided a notebook(example_data.ipynb) in the readme on how to convert pdb files to WebDataset format, but this document is gone. Can you update it? This is very important for us to use RLA for inference!

Sincerely looking forward to your help. Thank you very much!

**Comment by FosterBirnbaum** [comment]
Please see the recently updated [write_wds.ipynb](https://github.com/MadryLab/rla/blob/main/write_WDS.ipynb) file.
